version: "3.7"

networks:
  dex-network-1:
    driver: "bridge"

services:
  php-cli:
    build:
      dockerfile: docker/Dockerfile
      context: ./..
    volumes:
      - ../:/mnt/app
    links:
      - redis
    networks:
      - dex-network-1

  redis:
    image: redis:4.0
    container_name: dex_redis_1
    restart: always
    command:
      - 'redis-server'
      - '--loglevel ${REDIS_LOGLEVEL:-warning}'
      - '--databases 2'
      - '--save 900 1'
      - '--save 300 10'
      - '--save 60 10000'
      - '--maxmemory ${REDIS_MAXMEM:-50mb}'
    volumes:
      - ./redis/data:/data
    ports:
      - "6382:6379"
    networks:
      - dex-network-1